data:
  train_data: data/raw/train.csv
  save_path: data/processed
  processed_data: data/processed/processed.csv
  

data_split:
  random_state: 42
  test_size: 0.2

vectorizer:
  max_features: 5000
  vectorizer_path: "models/vectorizer.joblib"

model:
  type: logistic_regression

  logistic_regression:  
    max_iter: 200
    solver: liblinear
    class_weight: balanced

  svm:
    C: 1.0
    class_weight: balanced

  naive_bayes:
    alpha: 1.5

evaluation:
  saved_model = "models/model.pkl"